name: workout_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  pocketbase: ^0.23.0+1
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.0.7
  http: ^1.2.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/splash_loading_logo.png
    - assets/logo/login_image.png
    - assets/logo/default_avatar.png

    - assets/workouts/chest/chest_fly_(machine).png
    - assets/workouts/chest/incline_dumbbell_press.png
    - assets/workouts/chest/bench_press_barbell.png
    - assets/workouts/chest/incline_smith_press.png
    - assets/workouts/chest/flat_smith_press.png
    - assets/workouts/chest/machine_chest_press_flat.png
    - assets/workouts/chest/cabel_crossover.png

    - assets/workouts/back/lat_pulldown.png
    - assets/workouts/back/panta_lat_pulldown.png
    - assets/workouts/back/cabel_back_row.png
    - assets/workouts/back/machine_back_row.png
    - assets/workouts/back/tbar.png
    - assets/workouts/back/pull_up.png
    - assets/workouts/back/assisted_pullup.png
    - assets/workouts/back/lower_back_exten.png
    - assets/workouts/back/close_grip_lat_pulldown.png

    - assets/workouts/shoulder/face_pull.png
    - assets/workouts/shoulder/lateral_raise_cable.png
    - assets/workouts/shoulder/lateral_raise_dumbbell.png
    - assets/workouts/shoulder/lateral_raise_machine.png
    - assets/workouts/shoulder/reverse_fly_machine.png
    - assets/workouts/shoulder/shoulder_barbell_press.png
    - assets/workouts/shoulder/shoulder_dumbbell_press.png
    - assets/workouts/shoulder/shoulder_machine_press.png
    - assets/workouts/shoulder/dumbbell_shrug.png
    - assets/workouts/shoulder/machine_shrug.png

    - assets/workouts/tri/assisted_tri_dip.png
    - assets/workouts/tri/machine_dip.png
    - assets/workouts/tri/single_tri_push_down.png
    - assets/workouts/tri/tricep_extention.png
    - assets/workouts/tri/tricep_push_down.png

    - assets/workouts/bicep/barbell_curl.png
    - assets/workouts/bicep/bayesian_curl.png
    - assets/workouts/bicep/hammer_curl_cable.png
    - assets/workouts/bicep/preacher_curl.png
    - assets/workouts/bicep/seated_incline_curl.png

    - assets/workouts/abs/abs_twist.png
    - assets/workouts/abs/decline_setup.png
    - assets/workouts/abs/leg_raises.png
    - assets/workouts/abs/machine_abs_crunch.png

    - assets/workouts/legs/bulgarian_split_squat.png
    - assets/workouts/legs/squat.png
    - assets/workouts/legs/hack_squat.png
    - assets/workouts/legs/leg_press.png
    - assets/workouts/legs/leg_extention.png
    - assets/workouts/legs/seated_leg_curl.png
    - assets/workouts/legs/laying_leg_curl.png
    - assets/workouts/legs/rdl.png
    - assets/workouts/legs/deadlift.png
    - assets/workouts/legs/seated_calf_press.png
    - assets/workouts/legs/calf_raises.png
    - assets/workouts/legs/hip_thrust_barbell.png
    - assets/workouts/legs/seated_calf_raise.png

    - assets/workout_category/chest_emoji.png
    - assets/workout_category/abs_emoji.png
    - assets/workout_category/back_emoji.png
    - assets/workout_category/shoulders_emoji.png
    - assets/workout_category/tricep_emoji.png
    - assets/workout_category/bicep_emoji.png
    - assets/workout_category/cardio_emoji.png
    - assets/workout_category/legs_emoji.png
    - assets/workout_category/forearms_emoji.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
